login_route:
    path: /login
    defaults: { _controller: AppMainBundle:Security:login }

login_check:
    path: /login_check
    defaults: { _controller: AppMainBundle:Security:loginCheck }

app_main_security_register:
    path: /register
    defaults: { _controller: AppMainBundle:Security:register }

app_main_security_confirm:
    path: /confirm
    defaults: { _controller: AppMainBundle:Security:confirm }
